### PR TITLE
PEER-TO-PEER-REVIEW

### PR DESCRIPTION
**Pull request by EzekielUtshudi**
In This PR I Implemented :
-Javascript Best practice
-HTML best practice
-I practiced DRY, KISS, YAGNI

### CODE REVIEW

**Comment by Edward-Kabue** [comment]
DRY, KISS, YAGNI, and JavaScript best practice review.
I checked your code against JavaScript best practices, YAGNI, KISS, and DRY, I'm glad that you wrote your code in a professional way 👍

You managed to keep your code simple, and separate files which made it simple and easy to understand 😄

You had managed to not repeat any block of code with the same functionality however you reused the code which made your code so awesome 👌

Nothing else to add to your repo, keep your movement on 🍾

**Comment by EzekielUtshudi** [comment]
Thank you for the time you have taken to review my codes and I will do my best to keep applying the professional skills we are learning everyday.

**Review by Yazino12 — COMMENTED** [review]
## Hi @Yazino12   

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . Great job on following Javascript best practices. You followed all _DRY_, _KISS_, and _YAGNI_ rules.
# Status: Required Changes ♻️⛔️

- [x] Kindly add the Live link to your README.md

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me if something is not 100% clear.

**Review by Yazino12 — COMMENTED** [review]
Hi @Yazino12 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

clap

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_Keep up the good work_

**Review by EzekielUtshudi — COMMENTED** [review]
## STATUS: APPROVED :large_green_circle:
## Hi @Yazino12 :,
🥇 👍 you have done a great work, you repository is documented in a professional way. also your code is pretty clean following the JavaScript best practices
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada:
## To Highlight :tada:
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. :heavy_check_mark:

Cheers and Happy coding!:clap::clap::clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
(Not automatically expanded because 4 MB is too large. You can expand it anyway or open it in a new window.)

**Review by EzekielUtshudi — COMMENTED** [review]
Hey @Edward-Kabue ,
DRY, KISS, YAGNI, and JavaScript best practice review.
I checked your code against JavaScript best practices, YAGNI, KISS, and DRY, I'm glad that you wrote your code in a professional way 👍

You managed to keep your code simple, and separate files which made it simple and easy to understand 😄

You had managed to not repeat any block of code with the same functionality however you reused the code which made your code so awesome 👌

Nothing else to add to your repo, keep your movement on 🍾

**Pull request merged**
